# Generated by Django 5.1.1 on 2024-10-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uppers',
            new_name='upper',
        ),
    ]
